In [7]:
# G.K.: binary of 5 is 00000101 (1 byte) in binary.
# Why Numpy is faster than normal Python List?

# > Numpy:
# >> Numpy will convert it in int64 (8 bytes) format [defult].
# >> We can also change the format from int64 to int16 (2 bytes) or even int8 (1 byte).
# > List:
# >> In list uses int type for python. This build-in python is consist of 4 different things. 
# >> They are: 1. Size (4 bytes) 2. Reference Count (8 bytes) 3. Oject Type (8 bytes) 4. Oject Value (8bytes)
# > Basically, to just make a small list, the size will be big compare to NumPy. For this reason, Numpy is faster than (normal) Python List.

# In python list, the compiler has to check the type of each element. But, in Numpy the compiler doesn't have to do it. Hence, Numpy is fater than compiler.

# In list, computer uses different mamory location to store the items of the list where as, in NumPy, computers uses continues memory location. Also for this reason Numpy is faster as it doen't have to go to different different location to find the items.

#                                                                                                                             ___ 1
# G.K.: In multi dimentional arrays, axis = 0 means operations will heppen on "Column" wise while axis = 1 means "Row" wise. |
#                                                                                                                            0

In [8]:
import numpy as np

In [9]:
a = np.array([1, 2, 3, 'Aziz'])
b = np.array([[9, 5, 6], [3, 1, 8], [2, 9, 5]])
print(b)

[[9 5 6]
 [3 1 8]
 [2 9 5]]


In [59]:
# Get Dimension
b.ndim

2

In [11]:
# Get Shape
print(b.shape)
print(a.shape)

(3, 3)
(4,)


In [61]:
# Get Type
a.dtype

dtype('<U21')

In [65]:
a.size

4

In [13]:
# Get size of the items (it will show the size of the item which have the maximum size)
a.itemsize

84

In [67]:
# Get total size (no. of elements and no. of bytes)
b.size * b.itemsize
# or,
b.nbytes

72

In [15]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [79]:
# Taking specified elements of multiple indexes of the array.
print( c[0][[1, 4, 5]] ) # we're taking the 1st row of the matrix (consideriting it a list) and find the elements of the listed indxes
print( c[1, [1, 4, 5]] ) # Another way of doing the same thing

print(c[: ,[1, 4, 5]]) # Taking elements of specified columns. 

[2 5 6]
[ 9 12 13]
[[ 2  5  6]
 [ 9 12 13]]


In [ ]:
# Get all the elements of the first row
c[0, :]


array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get all the elements of the first column
c[:, 0]

array([1, 8])

In [19]:
# Getting more customized data [startindex:endindex:stepsize] <= here endindex is exclusive
print( c[0, 1:6:2] ) # First row's customized data
print( c[:, 1:6:2] ) # All rows' cutomized data

[2 4 6]
[[ 2  4  6]
 [ 9 11 13]]


In [20]:
# changeing data of the array
c[:, 3] = 77
print(c)

# changing using a subarray
c[:, 3] = [55, 66]
print(c)

[[ 1  2  3 77  5  6  7]
 [ 8  9 10 77 12 13 14]]
[[ 1  2  3 55  5  6  7]
 [ 8  9 10 66 12 13 14]]


###### *3-d exmaple

In [21]:
d = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
# Get specified elements (work outside in)
print( d[0, 1 , 1] )

4


#### Initialzing Different Types of Arrays

In [23]:
# All zeros(0s) matrix
np.zeros(5) # 1D array
np.zeros((2, 3)) # 2D array
np.zeros([2, 3, 3]) # 3D array
# This is how we can make multidimentional arrays and we can give duple of array as arrguements for specifying the size.

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# All ones (1s) matrix
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Matrix with any other specified number
np.full((2, 3), 88)

array([[88, 88, 88],
       [88, 88, 88]])

In [26]:
# Matrix with any other specified number but copying the size of other matrix
e = np.full_like(b, 33)  # here we are taking the size of b matrix but filling it with a specified number
print(e)

f = np.full(b.shape, 66) # otherway of doing the same task
print(f)

[[33 33 33]
 [33 33 33]
 [33 33 33]]
[[66 66 66]
 [66 66 66]
 [66 66 66]]


In [27]:
# Matix of Random decimal number
np.random.rand(2, 3)

array([[0.33544285, 0.67458612, 0.02964067],
       [0.65096123, 0.02764769, 0.23695013]])

In [124]:
# Matix of Random integer number
np.random.randint(10, size = (3, 3)) # Instead of 7 (by defaul 0 is the initial number), we can specify strting & ending num e.g. 3, 7

array([[9, 3, 4],
       [5, 5, 1],
       [5, 2, 4]], dtype=int32)

In [29]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# repeat an array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
repeated = np.repeat(arr, repeats=3, axis= 0)
repeated

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [128]:
array = np.ones((5, 5))
# width = array[0,:].size
# array[1:width-1, 1:width-1] = 0
# half = int(np.floor(width/2))
# array[half, half] = 9

inner_arr = np.zeros((3, 3))
inner_arr[1, 1] = 9
array[1:4, 1:4] = inner_arr

array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be careful when copying arrays!!!

In [32]:
g = np.array([1 , 2, 3])
h = g.copy()
h[0] = 100
h

array([100,   2,   3])

#### Mathematics

Math Opertions perfomed in element by element

In [33]:
g + 3

array([4, 5, 6])

In [34]:
g - 3

array([-2, -1,  0])

In [35]:
g * 3

array([3, 6, 9])

In [36]:
g / 3

array([0.33333333, 0.66666667, 1.        ])

In [37]:
g ** 3

array([ 1,  8, 27])

In [38]:
k = np.array([1, 0, -1])

g + k

array([2, 2, 2])

In [39]:
# Trigonometry
np.cos(k)

array([0.54030231, 1.        , 0.54030231])

**Linear Algebra**

In [40]:
i = np.ones([2, 3])
l = np.full((3, 2), 2)
print(i)
print(l)
# i * l <= won't work because the sape don't match. In element by element operation, the shaps of both matrices have to match.
np.matmul(i, l)  # this multiplication is called matrix multiplication (special kind of operation)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [41]:
# Find the determinant
m = np.identity(3)
np.linalg.det(m)

np.float64(1.0)

**Statistics**

In [129]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
# np.min(stats)
np.min(stats, axis=1) # mins of raws

array([1, 4])

In [ ]:
np.max(stats)
np.max(stats, axis=0) # maxs of columns 

array([4, 5, 6])

In [45]:
np.sum(stats, axis = 1)

array([ 6, 15])

**Reorganizing Arrays**

In [ ]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)

after = before.reshape((4, 2))
print(after)
# Important: Total number of elements of "before" has to match with "after"

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1, v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# Horizontal Stacking Vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Miscellaneous**\
Load Data From File

In [136]:
file_data = np.genfromtxt("Data1.txt", delimiter=",")
file_data = file_data.astype("int32")
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

**Boolean Masking and Advanced Indexing**

In [50]:
# boolean operation
file_data > 50  # reaturn bool value where the file_data is greater than 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [51]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [137]:
np.any(file_data > 50, axis=0) # it works kind of like "OR" operation. if any value of the axis fills the condition, it returns ture

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [138]:
np.all(file_data > 50, axis=0) # it works kind of like "AND" operation.If all values of the axis fills the condition, it returns False

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [54]:
((file_data > 50) & (file_data < 100)) # Complex operation
(~(file_data > 50) & (file_data < 100)) # Opposite operation


array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])